import { AfterContentInit, OnDestroy, EventEmitter, QueryList } from '@angular/core';
import { Subscription } from 'rxjs';
import { NgWizardDataService } from '../ng-wizard-data.service';
import { NgWizardConfig, NgWizardStep, ToolbarButton, StepChangedArgs } from '../../utils/interfaces';
import { THEME, STEP_DIRECTIN, STEP_POSITION } from '../../utils/enums';
export declare class NgWizardComponent implements OnDestroy, AfterContentInit {
    private ngWizardDataService;
    steps: QueryList<NgWizardStep>;
    _pConfig: NgWizardConfig;
    get pConfig(): NgWizardConfig;
    set pConfig(config: NgWizardConfig);
    config: NgWizardConfig;
    stepChanged: EventEmitter<StepChangedArgs>;
    themeChanged: EventEmitter<THEME>;
    reseted: EventEmitter<void>;
    styles: {
        main?: string;
        step?: string;
        previousButton?: string;
        nextButton?: string;
        toolbarTop?: string;
        toolbarBottom?: string;
    };
    showToolbarTop: boolean;
    showPreviousButton: boolean;
    showNextButton: boolean;
    showToolbarBottom: boolean;
    showExtraButtons: boolean;
    currentStepIndex: number;
    currentStep: NgWizardStep;
    resetWizardWatcher: Subscription;
    showNextStepWatcher: Subscription;
    showPreviousStepWatcher: Subscription;
    showStepWatcher: Subscription;
    setThemeWatcher: Subscription;
    constructor(ngWizardDataService: NgWizardDataService);
    ngAfterContentInit(): void;
    _init(): void;
    _initSteps(): void;
    _backupStepStates(): void;
    _restoreStepStates(): void;
    _initStyles(): void;
    _setToolbar(): void;
    _setEvents(): void;
    _getStepCssClass(selectedStep: NgWizardStep): string;
    _showSelectedStep(event: Event, selectedStep: NgWizardStep): boolean;
    _showNextStep(event?: Event): void;
    _showPreviousStep(event?: Event): void;
    _showStep(selectedStepIndex: number): Promise<void>;
    private _isStepChangeValid;
    _loadStepContent(selectedStep: NgWizardStep): void;
    _setAnchor(selectedStep: NgWizardStep): void;
    _setButtons(index: number): void;
    _extraButtonClicked(button: ToolbarButton): void;
    _keyNav(event: KeyboardEvent): void;
    _showLoader(): void;
    _hideLoader(): void;
    _getStepDirection(selectedStepIndex: number): STEP_DIRECTIN;
    _getStepPosition(selectedStepIndex: number): STEP_POSITION;
    _setTheme(theme: THEME): boolean;
    _reset(): void;
    ngOnDestroy(): void;
}
